version: 2
updates:
    - package-ecosystem: npm
      versioning-strategy: increase
      directory: /
      schedule:
          interval: weekly
      groups:
          minor-patch:
              applies-to: version-updates
              update-types:
                  - minor
                  - patch
      commit-message:
        prefix: fix(ignore)
      allow:
        - dependency-type: direct
          dependency-name: typescript
          versions:
            - "5.8.x"
    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: weekly